### ISSUE TITLE
老大可否保留一下trojan的一些老版本二进制文件？

### ISSUE THREAD

**Issue by babylife** [rampageX/arm-static-bins#1]
先膜拜下大神。全球貌似就您在做了，谢谢

**Comment by rampageX** [comment]
多老的？我用 trojan 是从 1.14.1 开始用的。

**Comment by babylife** [comment]
嗯嗯1.14.1开始就好了 我现在用的就是1.14.1，感觉您辛苦编译了 留存下也蛮好，也就是在多保留个文件夹啦 。再次感谢大神的贡献
