### ISSUE TITLE
大神，项目考虑集成编译下HAPROXY吗？

### ISSUE THREAD

**Issue by babylife** [rampageX/arm-static-bins#2]
https://github.com/haproxy/haproxy/releases/tag/v2.2-dev7
目前用的fanss插件还是1.8.8的，谢谢

![image](https://user-images.githubusercontent.com/31977161/81128828-e178f380-8f74-11ea-8b69-51f2640015b2.png)

**Comment by rampageX** [comment]
这个在路由器上用还是 1.8.x 系列性能比较好，2.x 占用资源很厉害，新功能基本也用不上。

我看看吧，跟 dev 版本就有点累。

**Comment by babylife** [comment]
有道理的，我到是忽略这点了，现在1.8.8还是没什么问题也稳定。 我觉得倒是不需要跟dev版本，最新的版本好像是2.1
http://git.haproxy.org/?p=haproxy-2.1.git

**Comment by babylife** [comment]
1.8.25好像是1.8的最新版本，是不是可以跟这个版本？也没有过eol的日期

![image](https://user-images.githubusercontent.com/31977161/81132985-d62cc480-8f82-11ea-99a1-d629d09474a0.png)

**Comment by rampageX** [comment]
已添加. 

dev 有什么吸引人的功能，比如说了很久的 udp 负载均衡，就更新下，要不就随缘了。

**Comment by babylife** [comment]
大佬威武！

**Comment by babylife** [comment]
![image](https://user-images.githubusercontent.com/31977161/81138985-9ff94000-8f96-11ea-87c0-7f99d51b2cbf.png)
直接使用Lite版本完美使用，好奇问问，和full版本有什么区别吗
