### ISSUE TITLE
关于Trojan BIN文件大小的一些小疑问

### ISSUE THREAD

**Issue by babylife** [rampageX/arm-static-bins#3]
大师您好，我想咨询下，HQ450的BIN文件和您的是一个版本的，为何大小差别很大？对性能上有什么影响吗？

https://github.com/hq450/fancyss/tree/master/trojan 
Executable File  1.37 MB 
![image](https://user-images.githubusercontent.com/31977161/81264016-4dda1c80-9073-11ea-96cf-53abea6e3df8.png)

**Comment by rampageX** [comment]
它用 UPX 压缩了。 `upx -9 trojan`

其实通常路由器固件本身的文件系统已经启用了压缩，所以在路由器上用的话用不用 upx 压缩无所谓的。当然分享时文件小很多，也是有用的。

压缩后的文件在一些性能比较低的路由器上启动会比不压缩稍微慢一点，因为有个（对用户透明的）解压过程。这个你自己试试就可以感觉到。

我之前也喜欢用压缩，后来基本不用了。实际运行后性能应该区别不大。

**Comment by babylife** [comment]
太感谢了！又学到了一个非常厉害的知识点
