### ISSUE TITLE
请教大神： lite版本和ALL版本有什么区别

### ISSUE THREAD

**Issue by babylife** [rampageX/arm-static-bins#4]
readme文档没有完全看明白，我当前一直使用lite版本没有问题，想咨询下

**Comment by rampageX** [comment]
HAPROXY?

All 版本就是带外置库的全功能版本 `USE_ZLIB=1 USE_OPENSSL=1 USE_LUA=1 USE_PCRE=1 USE_PCRE_JIT=1`, 由于集成的都是静态库，所以文件会比较大。All 版本一般用不上；

Lite 就是不带外置库了，功能都由 HAPROXY 自带的源码来支持，通常够用了。

**Comment by babylife** [comment]
嗯好的，谢谢，明白了！

**Comment by babylife** [comment]
大神威武

**Comment by rampageX** [comment]
下次问题解决自己关下 issue ...
